# Intent: enforce pull request rules such as title conventions
name: Enforce pull request rules
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  pr_title_naming_convention:
    runs-on: ubuntu-latest
    steps:
      - name: Check for [VW-##] prefix
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^\[VW-[0-9]+\]\s.+'
          verbal_description: "PR title must start with [VW-##] (referencing the relevant Jira ticket) followed by a short description. Feel free to use [VW-0] for a quick cleanup that does not have an associated ticket."
