# Intent: enforce pull request rules such as title conventions
name: Enforce pull request rules
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  pr_title_naming_convention:
    runs-on: ubuntu-latest
    steps:
      - name: Check for [VW-##] prefix
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '^\[VW-[0-9]+\]\s.+'
